# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.16.4/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.16.4/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/baris/uhsNN

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/baris/uhsNN

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.16.4/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.16.4/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/baris/uhsNN/CMakeFiles /Users/baris/uhsNN/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/baris/uhsNN/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named predict

# Build rule for target.
predict: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 predict
.PHONY : predict

# fast build rule for target.
predict/fast:
	$(MAKE) -f CMakeFiles/predict.dir/build.make CMakeFiles/predict.dir/build
.PHONY : predict/fast

predict.o: predict.cc.o

.PHONY : predict.o

# target to build an object file
predict.cc.o:
	$(MAKE) -f CMakeFiles/predict.dir/build.make CMakeFiles/predict.dir/predict.cc.o
.PHONY : predict.cc.o

predict.i: predict.cc.i

.PHONY : predict.i

# target to preprocess a source file
predict.cc.i:
	$(MAKE) -f CMakeFiles/predict.dir/build.make CMakeFiles/predict.dir/predict.cc.i
.PHONY : predict.cc.i

predict.s: predict.cc.s

.PHONY : predict.s

# target to generate assembly for a file
predict.cc.s:
	$(MAKE) -f CMakeFiles/predict.dir/build.make CMakeFiles/predict.dir/predict.cc.s
.PHONY : predict.cc.s

src/baseLayer.o: src/baseLayer.cc.o

.PHONY : src/baseLayer.o

# target to build an object file
src/baseLayer.cc.o:
	$(MAKE) -f CMakeFiles/predict.dir/build.make CMakeFiles/predict.dir/src/baseLayer.cc.o
.PHONY : src/baseLayer.cc.o

src/baseLayer.i: src/baseLayer.cc.i

.PHONY : src/baseLayer.i

# target to preprocess a source file
src/baseLayer.cc.i:
	$(MAKE) -f CMakeFiles/predict.dir/build.make CMakeFiles/predict.dir/src/baseLayer.cc.i
.PHONY : src/baseLayer.cc.i

src/baseLayer.s: src/baseLayer.cc.s

.PHONY : src/baseLayer.s

# target to generate assembly for a file
src/baseLayer.cc.s:
	$(MAKE) -f CMakeFiles/predict.dir/build.make CMakeFiles/predict.dir/src/baseLayer.cc.s
.PHONY : src/baseLayer.cc.s

src/layers/activation.o: src/layers/activation.cc.o

.PHONY : src/layers/activation.o

# target to build an object file
src/layers/activation.cc.o:
	$(MAKE) -f CMakeFiles/predict.dir/build.make CMakeFiles/predict.dir/src/layers/activation.cc.o
.PHONY : src/layers/activation.cc.o

src/layers/activation.i: src/layers/activation.cc.i

.PHONY : src/layers/activation.i

# target to preprocess a source file
src/layers/activation.cc.i:
	$(MAKE) -f CMakeFiles/predict.dir/build.make CMakeFiles/predict.dir/src/layers/activation.cc.i
.PHONY : src/layers/activation.cc.i

src/layers/activation.s: src/layers/activation.cc.s

.PHONY : src/layers/activation.s

# target to generate assembly for a file
src/layers/activation.cc.s:
	$(MAKE) -f CMakeFiles/predict.dir/build.make CMakeFiles/predict.dir/src/layers/activation.cc.s
.PHONY : src/layers/activation.cc.s

src/layers/batchNormalization.o: src/layers/batchNormalization.cc.o

.PHONY : src/layers/batchNormalization.o

# target to build an object file
src/layers/batchNormalization.cc.o:
	$(MAKE) -f CMakeFiles/predict.dir/build.make CMakeFiles/predict.dir/src/layers/batchNormalization.cc.o
.PHONY : src/layers/batchNormalization.cc.o

src/layers/batchNormalization.i: src/layers/batchNormalization.cc.i

.PHONY : src/layers/batchNormalization.i

# target to preprocess a source file
src/layers/batchNormalization.cc.i:
	$(MAKE) -f CMakeFiles/predict.dir/build.make CMakeFiles/predict.dir/src/layers/batchNormalization.cc.i
.PHONY : src/layers/batchNormalization.cc.i

src/layers/batchNormalization.s: src/layers/batchNormalization.cc.s

.PHONY : src/layers/batchNormalization.s

# target to generate assembly for a file
src/layers/batchNormalization.cc.s:
	$(MAKE) -f CMakeFiles/predict.dir/build.make CMakeFiles/predict.dir/src/layers/batchNormalization.cc.s
.PHONY : src/layers/batchNormalization.cc.s

src/layers/conv1d.o: src/layers/conv1d.cc.o

.PHONY : src/layers/conv1d.o

# target to build an object file
src/layers/conv1d.cc.o:
	$(MAKE) -f CMakeFiles/predict.dir/build.make CMakeFiles/predict.dir/src/layers/conv1d.cc.o
.PHONY : src/layers/conv1d.cc.o

src/layers/conv1d.i: src/layers/conv1d.cc.i

.PHONY : src/layers/conv1d.i

# target to preprocess a source file
src/layers/conv1d.cc.i:
	$(MAKE) -f CMakeFiles/predict.dir/build.make CMakeFiles/predict.dir/src/layers/conv1d.cc.i
.PHONY : src/layers/conv1d.cc.i

src/layers/conv1d.s: src/layers/conv1d.cc.s

.PHONY : src/layers/conv1d.s

# target to generate assembly for a file
src/layers/conv1d.cc.s:
	$(MAKE) -f CMakeFiles/predict.dir/build.make CMakeFiles/predict.dir/src/layers/conv1d.cc.s
.PHONY : src/layers/conv1d.cc.s

src/layers/conv2d.o: src/layers/conv2d.cc.o

.PHONY : src/layers/conv2d.o

# target to build an object file
src/layers/conv2d.cc.o:
	$(MAKE) -f CMakeFiles/predict.dir/build.make CMakeFiles/predict.dir/src/layers/conv2d.cc.o
.PHONY : src/layers/conv2d.cc.o

src/layers/conv2d.i: src/layers/conv2d.cc.i

.PHONY : src/layers/conv2d.i

# target to preprocess a source file
src/layers/conv2d.cc.i:
	$(MAKE) -f CMakeFiles/predict.dir/build.make CMakeFiles/predict.dir/src/layers/conv2d.cc.i
.PHONY : src/layers/conv2d.cc.i

src/layers/conv2d.s: src/layers/conv2d.cc.s

.PHONY : src/layers/conv2d.s

# target to generate assembly for a file
src/layers/conv2d.cc.s:
	$(MAKE) -f CMakeFiles/predict.dir/build.make CMakeFiles/predict.dir/src/layers/conv2d.cc.s
.PHONY : src/layers/conv2d.cc.s

src/layers/dense.o: src/layers/dense.cc.o

.PHONY : src/layers/dense.o

# target to build an object file
src/layers/dense.cc.o:
	$(MAKE) -f CMakeFiles/predict.dir/build.make CMakeFiles/predict.dir/src/layers/dense.cc.o
.PHONY : src/layers/dense.cc.o

src/layers/dense.i: src/layers/dense.cc.i

.PHONY : src/layers/dense.i

# target to preprocess a source file
src/layers/dense.cc.i:
	$(MAKE) -f CMakeFiles/predict.dir/build.make CMakeFiles/predict.dir/src/layers/dense.cc.i
.PHONY : src/layers/dense.cc.i

src/layers/dense.s: src/layers/dense.cc.s

.PHONY : src/layers/dense.s

# target to generate assembly for a file
src/layers/dense.cc.s:
	$(MAKE) -f CMakeFiles/predict.dir/build.make CMakeFiles/predict.dir/src/layers/dense.cc.s
.PHONY : src/layers/dense.cc.s

src/layers/elu.o: src/layers/elu.cc.o

.PHONY : src/layers/elu.o

# target to build an object file
src/layers/elu.cc.o:
	$(MAKE) -f CMakeFiles/predict.dir/build.make CMakeFiles/predict.dir/src/layers/elu.cc.o
.PHONY : src/layers/elu.cc.o

src/layers/elu.i: src/layers/elu.cc.i

.PHONY : src/layers/elu.i

# target to preprocess a source file
src/layers/elu.cc.i:
	$(MAKE) -f CMakeFiles/predict.dir/build.make CMakeFiles/predict.dir/src/layers/elu.cc.i
.PHONY : src/layers/elu.cc.i

src/layers/elu.s: src/layers/elu.cc.s

.PHONY : src/layers/elu.s

# target to generate assembly for a file
src/layers/elu.cc.s:
	$(MAKE) -f CMakeFiles/predict.dir/build.make CMakeFiles/predict.dir/src/layers/elu.cc.s
.PHONY : src/layers/elu.cc.s

src/layers/embedding.o: src/layers/embedding.cc.o

.PHONY : src/layers/embedding.o

# target to build an object file
src/layers/embedding.cc.o:
	$(MAKE) -f CMakeFiles/predict.dir/build.make CMakeFiles/predict.dir/src/layers/embedding.cc.o
.PHONY : src/layers/embedding.cc.o

src/layers/embedding.i: src/layers/embedding.cc.i

.PHONY : src/layers/embedding.i

# target to preprocess a source file
src/layers/embedding.cc.i:
	$(MAKE) -f CMakeFiles/predict.dir/build.make CMakeFiles/predict.dir/src/layers/embedding.cc.i
.PHONY : src/layers/embedding.cc.i

src/layers/embedding.s: src/layers/embedding.cc.s

.PHONY : src/layers/embedding.s

# target to generate assembly for a file
src/layers/embedding.cc.s:
	$(MAKE) -f CMakeFiles/predict.dir/build.make CMakeFiles/predict.dir/src/layers/embedding.cc.s
.PHONY : src/layers/embedding.cc.s

src/layers/flatten.o: src/layers/flatten.cc.o

.PHONY : src/layers/flatten.o

# target to build an object file
src/layers/flatten.cc.o:
	$(MAKE) -f CMakeFiles/predict.dir/build.make CMakeFiles/predict.dir/src/layers/flatten.cc.o
.PHONY : src/layers/flatten.cc.o

src/layers/flatten.i: src/layers/flatten.cc.i

.PHONY : src/layers/flatten.i

# target to preprocess a source file
src/layers/flatten.cc.i:
	$(MAKE) -f CMakeFiles/predict.dir/build.make CMakeFiles/predict.dir/src/layers/flatten.cc.i
.PHONY : src/layers/flatten.cc.i

src/layers/flatten.s: src/layers/flatten.cc.s

.PHONY : src/layers/flatten.s

# target to generate assembly for a file
src/layers/flatten.cc.s:
	$(MAKE) -f CMakeFiles/predict.dir/build.make CMakeFiles/predict.dir/src/layers/flatten.cc.s
.PHONY : src/layers/flatten.cc.s

src/layers/locally1d.o: src/layers/locally1d.cc.o

.PHONY : src/layers/locally1d.o

# target to build an object file
src/layers/locally1d.cc.o:
	$(MAKE) -f CMakeFiles/predict.dir/build.make CMakeFiles/predict.dir/src/layers/locally1d.cc.o
.PHONY : src/layers/locally1d.cc.o

src/layers/locally1d.i: src/layers/locally1d.cc.i

.PHONY : src/layers/locally1d.i

# target to preprocess a source file
src/layers/locally1d.cc.i:
	$(MAKE) -f CMakeFiles/predict.dir/build.make CMakeFiles/predict.dir/src/layers/locally1d.cc.i
.PHONY : src/layers/locally1d.cc.i

src/layers/locally1d.s: src/layers/locally1d.cc.s

.PHONY : src/layers/locally1d.s

# target to generate assembly for a file
src/layers/locally1d.cc.s:
	$(MAKE) -f CMakeFiles/predict.dir/build.make CMakeFiles/predict.dir/src/layers/locally1d.cc.s
.PHONY : src/layers/locally1d.cc.s

src/layers/locally2d.o: src/layers/locally2d.cc.o

.PHONY : src/layers/locally2d.o

# target to build an object file
src/layers/locally2d.cc.o:
	$(MAKE) -f CMakeFiles/predict.dir/build.make CMakeFiles/predict.dir/src/layers/locally2d.cc.o
.PHONY : src/layers/locally2d.cc.o

src/layers/locally2d.i: src/layers/locally2d.cc.i

.PHONY : src/layers/locally2d.i

# target to preprocess a source file
src/layers/locally2d.cc.i:
	$(MAKE) -f CMakeFiles/predict.dir/build.make CMakeFiles/predict.dir/src/layers/locally2d.cc.i
.PHONY : src/layers/locally2d.cc.i

src/layers/locally2d.s: src/layers/locally2d.cc.s

.PHONY : src/layers/locally2d.s

# target to generate assembly for a file
src/layers/locally2d.cc.s:
	$(MAKE) -f CMakeFiles/predict.dir/build.make CMakeFiles/predict.dir/src/layers/locally2d.cc.s
.PHONY : src/layers/locally2d.cc.s

src/layers/lstm.o: src/layers/lstm.cc.o

.PHONY : src/layers/lstm.o

# target to build an object file
src/layers/lstm.cc.o:
	$(MAKE) -f CMakeFiles/predict.dir/build.make CMakeFiles/predict.dir/src/layers/lstm.cc.o
.PHONY : src/layers/lstm.cc.o

src/layers/lstm.i: src/layers/lstm.cc.i

.PHONY : src/layers/lstm.i

# target to preprocess a source file
src/layers/lstm.cc.i:
	$(MAKE) -f CMakeFiles/predict.dir/build.make CMakeFiles/predict.dir/src/layers/lstm.cc.i
.PHONY : src/layers/lstm.cc.i

src/layers/lstm.s: src/layers/lstm.cc.s

.PHONY : src/layers/lstm.s

# target to generate assembly for a file
src/layers/lstm.cc.s:
	$(MAKE) -f CMakeFiles/predict.dir/build.make CMakeFiles/predict.dir/src/layers/lstm.cc.s
.PHONY : src/layers/lstm.cc.s

src/layers/maxPooling2d.o: src/layers/maxPooling2d.cc.o

.PHONY : src/layers/maxPooling2d.o

# target to build an object file
src/layers/maxPooling2d.cc.o:
	$(MAKE) -f CMakeFiles/predict.dir/build.make CMakeFiles/predict.dir/src/layers/maxPooling2d.cc.o
.PHONY : src/layers/maxPooling2d.cc.o

src/layers/maxPooling2d.i: src/layers/maxPooling2d.cc.i

.PHONY : src/layers/maxPooling2d.i

# target to preprocess a source file
src/layers/maxPooling2d.cc.i:
	$(MAKE) -f CMakeFiles/predict.dir/build.make CMakeFiles/predict.dir/src/layers/maxPooling2d.cc.i
.PHONY : src/layers/maxPooling2d.cc.i

src/layers/maxPooling2d.s: src/layers/maxPooling2d.cc.s

.PHONY : src/layers/maxPooling2d.s

# target to generate assembly for a file
src/layers/maxPooling2d.cc.s:
	$(MAKE) -f CMakeFiles/predict.dir/build.make CMakeFiles/predict.dir/src/layers/maxPooling2d.cc.s
.PHONY : src/layers/maxPooling2d.cc.s

src/model.o: src/model.cc.o

.PHONY : src/model.o

# target to build an object file
src/model.cc.o:
	$(MAKE) -f CMakeFiles/predict.dir/build.make CMakeFiles/predict.dir/src/model.cc.o
.PHONY : src/model.cc.o

src/model.i: src/model.cc.i

.PHONY : src/model.i

# target to preprocess a source file
src/model.cc.i:
	$(MAKE) -f CMakeFiles/predict.dir/build.make CMakeFiles/predict.dir/src/model.cc.i
.PHONY : src/model.cc.i

src/model.s: src/model.cc.s

.PHONY : src/model.s

# target to generate assembly for a file
src/model.cc.s:
	$(MAKE) -f CMakeFiles/predict.dir/build.make CMakeFiles/predict.dir/src/model.cc.s
.PHONY : src/model.cc.s

src/tensor.o: src/tensor.cc.o

.PHONY : src/tensor.o

# target to build an object file
src/tensor.cc.o:
	$(MAKE) -f CMakeFiles/predict.dir/build.make CMakeFiles/predict.dir/src/tensor.cc.o
.PHONY : src/tensor.cc.o

src/tensor.i: src/tensor.cc.i

.PHONY : src/tensor.i

# target to preprocess a source file
src/tensor.cc.i:
	$(MAKE) -f CMakeFiles/predict.dir/build.make CMakeFiles/predict.dir/src/tensor.cc.i
.PHONY : src/tensor.cc.i

src/tensor.s: src/tensor.cc.s

.PHONY : src/tensor.s

# target to generate assembly for a file
src/tensor.cc.s:
	$(MAKE) -f CMakeFiles/predict.dir/build.make CMakeFiles/predict.dir/src/tensor.cc.s
.PHONY : src/tensor.cc.s

src/utils.o: src/utils.cc.o

.PHONY : src/utils.o

# target to build an object file
src/utils.cc.o:
	$(MAKE) -f CMakeFiles/predict.dir/build.make CMakeFiles/predict.dir/src/utils.cc.o
.PHONY : src/utils.cc.o

src/utils.i: src/utils.cc.i

.PHONY : src/utils.i

# target to preprocess a source file
src/utils.cc.i:
	$(MAKE) -f CMakeFiles/predict.dir/build.make CMakeFiles/predict.dir/src/utils.cc.i
.PHONY : src/utils.cc.i

src/utils.s: src/utils.cc.s

.PHONY : src/utils.s

# target to generate assembly for a file
src/utils.cc.s:
	$(MAKE) -f CMakeFiles/predict.dir/build.make CMakeFiles/predict.dir/src/utils.cc.s
.PHONY : src/utils.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... predict"
	@echo "... predict.o"
	@echo "... predict.i"
	@echo "... predict.s"
	@echo "... src/baseLayer.o"
	@echo "... src/baseLayer.i"
	@echo "... src/baseLayer.s"
	@echo "... src/layers/activation.o"
	@echo "... src/layers/activation.i"
	@echo "... src/layers/activation.s"
	@echo "... src/layers/batchNormalization.o"
	@echo "... src/layers/batchNormalization.i"
	@echo "... src/layers/batchNormalization.s"
	@echo "... src/layers/conv1d.o"
	@echo "... src/layers/conv1d.i"
	@echo "... src/layers/conv1d.s"
	@echo "... src/layers/conv2d.o"
	@echo "... src/layers/conv2d.i"
	@echo "... src/layers/conv2d.s"
	@echo "... src/layers/dense.o"
	@echo "... src/layers/dense.i"
	@echo "... src/layers/dense.s"
	@echo "... src/layers/elu.o"
	@echo "... src/layers/elu.i"
	@echo "... src/layers/elu.s"
	@echo "... src/layers/embedding.o"
	@echo "... src/layers/embedding.i"
	@echo "... src/layers/embedding.s"
	@echo "... src/layers/flatten.o"
	@echo "... src/layers/flatten.i"
	@echo "... src/layers/flatten.s"
	@echo "... src/layers/locally1d.o"
	@echo "... src/layers/locally1d.i"
	@echo "... src/layers/locally1d.s"
	@echo "... src/layers/locally2d.o"
	@echo "... src/layers/locally2d.i"
	@echo "... src/layers/locally2d.s"
	@echo "... src/layers/lstm.o"
	@echo "... src/layers/lstm.i"
	@echo "... src/layers/lstm.s"
	@echo "... src/layers/maxPooling2d.o"
	@echo "... src/layers/maxPooling2d.i"
	@echo "... src/layers/maxPooling2d.s"
	@echo "... src/model.o"
	@echo "... src/model.i"
	@echo "... src/model.s"
	@echo "... src/tensor.o"
	@echo "... src/tensor.i"
	@echo "... src/tensor.s"
	@echo "... src/utils.o"
	@echo "... src/utils.i"
	@echo "... src/utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

